# Generated by Django 4.2.1 on 2023-06-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="detection",
            new_name="detected_object",
        ),
    ]
