# Generated by Django 4.2.1 on 2023-06-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0002_rename_detection_location_detected_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location_test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
