# Generated by Django 4.2.1 on 2023-06-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0003_location_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="fixed",
            field=models.BooleanField(default=False),
        ),
    ]
