# Generated by Django 4.2.1 on 2023-06-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0004_location_fixed"),
    ]

    operations = [
        migrations.AddField(
            model_name="location_test",
            name="detect_type",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
