# Generated by Django 4.2.1 on 2023-06-21 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="photos",
        ),
        migrations.AddField(
            model_name="post",
            name="photo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="post.photo",
            ),
        ),
    ]
