# Generated by Django 4.2.1 on 2023-06-23 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="latitude",
            new_name="post_latitude",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="longitude",
            new_name="post_longitude",
        ),
    ]
