# Generated by Django 4.2.1 on 2023-06-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_remove_post_photos_post_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="photo",
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
