# Generated by Django 4.2.1 on 2023-06-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_rename_latitude_post_post_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("none", "신고 유형"),
                    ("road_damage", "도로 파손"),
                    ("road_barrier_damage", "도로 분리대 파손 또는 노후화"),
                    ("lane", "차선"),
                    ("crosswalk", "횡단보도"),
                    ("traffic_light", "신호등"),
                    ("guide_post", "시선 유도봉"),
                    ("speed_bump", "방지턱"),
                    ("guardrail", "가드레일"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
