# Generated by Django 4.2.1 on 2023-06-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_remove_post_author_remove_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
