# Generated by Django 4.2 on 2023-07-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_post_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="detected_image",
            field=models.ImageField(blank=True, null=True, upload_to="detected/"),
        ),
    ]
