# Generated by Django 4.2.1 on 2023-06-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_rename_content_post_post_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
