# Generated by Django 4.2 on 2023-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_detected_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="detected_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
