# Generated by Django 4.2 on 2023-07-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_detected_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("none", "신고 유형"),
                    ("bollard", "볼라드 손상"),
                    ("crosswalk", "횡단보도 손상"),
                    ("snowbox", "제설함 손상"),
                    ("pothole", "포트홀"),
                    ("road_barrier_damage", "도로 분리대 손상"),
                    ("lane", "도로 표시 손상"),
                    ("speed_bump", "방지턱"),
                    ("tubular_marker", "시선 유도봉"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
