# Generated by Django 4.2.1 on 2023-07-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("join", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="region",
            field=models.CharField(default=" ", max_length=150),
        ),
    ]
