# Generated by Django 4.2.1 on 2023-06-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_detection"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="is_checked",
            field=models.BooleanField(default=False),
        ),
    ]
