# Generated by Django 4.2.1 on 2023-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0004_damage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detection",
            old_name="timestamp",
            new_name="detected_time",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="frame",
        ),
        migrations.RemoveField(
            model_name="detection",
            name="is_checked",
        ),
        migrations.AddField(
            model_name="detection",
            name="detected_where",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="detection",
            name="image_path",
            field=models.URLField(),
        ),
    ]
