# Generated by Django 4.2.1 on 2023-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0005_rename_timestamp_detection_detected_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detection",
            name="image_path",
            field=models.URLField(null=True),
        ),
    ]
