# Generated by Django 4.2 on 2023-06-27 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0007_alter_detection_detected_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Detected",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("detected_object", models.CharField(max_length=200, null=True)),
                ("detected_time", models.CharField(max_length=200, null=True)),
                ("detected_where", models.CharField(max_length=200, null=True)),
                ("image_path", models.URLField(null=True)),
                (
                    "video",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="video.video",
                    ),
                ),
            ],
        ),
    ]
