# Generated by Django 4.2 on 2023-06-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0008_detected"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detected",
            name="image_path",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
