# Generated by Django 4.2 on 2023-06-27 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0009_alter_detected_image_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detected",
            name="video",
        ),
    ]
