# Generated by Django 4.2 on 2023-06-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0010_remove_detected_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_file",
        ),
        migrations.AlterField(
            model_name="detected",
            name="image_path",
            field=models.ImageField(blank=True, null=True, upload_to="video/"),
        ),
    ]
