# Generated by Django 4.2 on 2023-06-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0011_remove_video_video_file_alter_detected_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(default=1, upload_to=""),
        ),
    ]
