# Generated by Django 4.2 on 2023-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0012_video_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detected",
            name="image_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
