# Generated by Django 4.2.1 on 2023-07-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0013_alter_detected_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="detected",
            name="video_region",
            field=models.CharField(default=" ", max_length=150),
        ),
    ]
